### ISSUE TITLE
Default layers - NSA only

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website#3]
Remove IXPs and IPT sites from the  default layers, leaving just NSA site icons.

**Comment by agamba** [comment]
The layers have been removed from default loading. Be sure to clear cash in browser to see this change

**Comment by Andrew-Clement** [comment]
Thanks for the fast response, but I meant that the NSA layer be kept on by default (dropping only the IXP and IPT sites.)

A>

On 2016-06-29, at 3:06 PM, Antonio Gamba-Bari <notifications@github.com> wrote:

Closed #3.

**Comment by Andrew-Clement** [comment]
I  did clear my cache and see that all default layers have been removed. I would like the NSA layer to be on by default.

On 2016-06-29, at 3:06 PM, Antonio Gamba-Bari <notifications@github.com> wrote:

The layers have been removed from default loading. Be sure to clear cash in browser to see this change

**Comment by colinmccann** [comment]
Anto fixed this

**Comment by agamba** [comment]
Reopen this because there is still a bug I just noticed. The layer NSA keeps turning on and off every time you submit a custom query. This has been there for a while but we didn't catch it. It requires rethinking how are we modelling and re-rendering the default layers every time the map is refreshed with a new query.
For reference, here is where the bug occurs
https://github.com/ixmaps/website/blob/master/js/ixmaps.gm.js#L172

**Comment by colinmccann** [comment]
This seems fixed to me - NSA stays on after. closing again
