### ISSUE TITLE
Explore page - Mysteriously Search doesn't return sometimes??

### ISSUE THREAD

**Issue by Andrew-Clement** [ixmaps/website#7]
Search sometimes doesn't return for specific terms.
eg submitter = DangerDiabolik  (which has 2023 routes in the DB)
eg origin city = Victoria 
after Canceling, can still do successful searches on other terms

**Comment by colinmccann** [comment]
ixmaps=> select * from full_routes_large where submitter like '%anger%' and hop = 1;
 traceroute_id | hop | ip_addr | hostname | asnum | mm_lat | mm_long | lat | long | mm_city | mm_region | mm_country | mm_postal | gl_override | dest | dest_ip | sub_time | submitter | zip_code | short_name 
---------------+-----+---------+----------+-------+--------+---------+-----+------+---------+-----------+------------+-----------+-------------+------+---------+----------+-----------+----------+------------
(0 rows)

That would be why - this is not an explore page issue, it's a geolocation issue.

We don't get a 'no routes found' error message here because we never get around to submitting the route. We get lost somewhere in /application/controller/explore_controller.php. That's an Anto debugging job...

**Comment by Andrew-Clement** [comment]
OK, but then how is that you show DangerDiabolik contributing 2023 routes?  We need consistency between the sql queries you use and what shows up in Explore page queries. Why is there a discrepancy? How can it be addressed?

**Comment by colinmccann** [comment]
Has has contributed 2023 routes - none of which have a geolocated hop 1, which is crucial to determining origin city

**Comment by Andrew-Clement** [comment]
I think there are two issues getting conflated here: 
1. Search not returning -  involves waiting, waiting, and then clicking Cancel 
   This a major problem apart from whether or not there are any results to be found (and the focus of this issue)
2. Search not finding routes when there should be some (this is the subject of a different issue #8
